### PR TITLE
:construction: Launch pad UI components

### LINKED ISSUE #931: Feature: Launch pad components
# ℹ Overview

### PR DESCRIPTION
**Pull request by treasurechic**
# ℹ Overview

### 🔐 Acceptance:

- [ ] `yarn test` passes

### CODE REVIEW

**Review by stephclarkga — CHANGES_REQUESTED** [review]
Components look good!

One thing is all of these should open an "enter address" box when turned on.
Screen Shot 2023-02-06 at 9 07 35 AM

And the "Algodex Mailbox" text shouldn't change when hovered and should keep a regular cursor instead of the text cursor.
https://user-images.githubusercontent.com/59464107/216993830-dcda6823-343f-464a-80a9-385736babb55.mov

That's all I see right now though! Nice work!

**Comment by treasurechic** [comment]
> Components look good!
> 
> One thing is all of these should open an "enter address" box when turned on. Screen Shot 2023-02-06 at 9 07 35 AM
> 
> And the "Algodex Mailbox" text shouldn't change when hovered and should keep a regular cursor instead of the text cursor. https://user-images.githubusercontent.com/59464107/216993830-dcda6823-343f-464a-80a9-385736babb55.mov
> 
> That's all I see right now though! Nice work!

Ok, will fix and update those

**Review by ericsharma — CHANGES_REQUESTED** [review]
@treasurechic As far as I'm concerned this is looking great! The only change I want to request is changing the branch source for this PR. We don't want to merge the launchpad designs into development until the feature is actually functioning.

 Instead can you **open the pr into #944** ? I created an issue tracking branch for the Launchpad feature and it is using #896 as a source, which has the new wallet management system.

**Comment by treasurechic** [comment]
> @treasurechic As far as I'm concerned this is looking great! The only change I want to request is changing the branch source for this PR. We don't want to merge the launchpad designs into development until the feature is actually functioning.
> 
> Instead can you **open the pr into #944** ? I created an issue tracking branch for the Launchpad feature and it is using #896 as a source, which has the new wallet management system.

Alright, got it 👍🏽

**Comment by treasurechic** [comment]
Opening the PR to another branch

**Pull request closed without merging**
