### PR TITLE
Issue 935 feature search filter and sorting by spread

### LINKED ISSUE #935: Feature: Search Filter and Sorting by Spread
# ℹ Overview
Implementation for searching and sorting

### PR DESCRIPTION
**Pull request by IYTEC**
# ℹ Overview
Filtering feature for search form

### 📝 Related Issues
- closes #935 

### 🔐 Acceptance:

- [ ] `yarn test` passes

### CODE REVIEW

**Review by ericsharma — CHANGES_REQUESTED** [review]
Can you please delete any unused code? For example lines 190-220 in `SearchInput.jsx`?

**Review by stephclarkga — CHANGES_REQUESTED** [review]
Couple things I see:

Small visual thing, can you move the "More Filters" button over a bit to match the indentation of the checkboxes with the search bar on the left. Basically that dropdown arrow should have a small indent from the right to fit below the Search bar. Let me know if that doesn't make sense and I'll get a better image.
Screen Shot 2023-02-28 at 9 49 38 AM

When the sliders are set to 0, I think the option should automatically uncheck itself if that's possible. I also think we should also change the scale of the "Price" slider - I think it should include some decimals on the low end. Maybe range from .1 to 5000 at the high end. There are very few assets that are over 5000 that it would limit the list down quite a bit. I think few assets will ever be 500,000 ALGOs. I'd love if this could be a double slider where you can set a floor and a ceiling (this would also be applicable to age of project if we can set high and lows there to search in between I think it's more useful)
Screen Shot 2023-02-28 at 9 54 51 AM

**Comment by ericsharma** [comment]
@stephclarkga I agree with most of all your feedback but not sure how I feel about hard coding the range for the price slider. goBTC is a very important asset and is definitely way over 5000 algo and goEth will go above 5000 algo every once in a while. To compensate for the outliers with very high price I advised @IYTEC to use a logarithmic scale for the slider. If you play around with it you will see that the price slider you will see that it gives greater precision for smaller prices and less precision for larger ones.

**Comment by IYTEC** [comment]
@stephclarkga, I have made the changes noted. I don't think we can have the decimals for the slider because the sliders are logarithmic (like @ericsharma pointed). I also thing having the Slider at one covers for assets that are less than 1 but greater than 0.

Please help me go over and let me know what you think.

**Review by stephclarkga — CHANGES_REQUESTED** [review]
Understood about the price scale and I see how it has more precision on the smaller end of the scale but I feel like more granularity could be useful if most of the assets are below 1 ALGO. It'd be nice to see data on where prices for most commonly traded ASAs fall. But I think it's okay to leave it like this.
 
Are we able to have a double slider like this though where users can set a floor and a ceiling? Default state would start inactive with a slider at each end of the scale should be able to drag the slider from either end to be able to filter both directions.
Screen Shot 2023-03-01 at 3 57 01 PM

**Comment by ericsharma** [comment]
@IYTEC Are you working on @stephclarkga suggestions related to the double slider?

**Comment by IYTEC** [comment]
> @IYTEC Are you working on @stephclarkga suggestions related to the double slider?

Yes. Working on this.
Will push soon.

**Comment by IYTEC** [comment]
@stephclarkga please help confirm if it works as expected. @ericsharma, I remove the functionality to uncheck the box when slider is set to 0, because we have double sliding points now.

Please let me know what you think.

**Review by stephclarkga — CHANGES_REQUESTED** [review]
1. The sliders should default to having a slider on both ends of the scale to begin with (since we default to not filtering anything, they are all inclusive). Like this: 
Screen Shot 2023-03-06 at 1 54 09 PM

Even when they are turned off, I think they should default to having a slider at each end since it makes more sense to adjust from each end and see that that's a possibility than to pull both from the floor.


2. There's some weird behavior where dragging a slider to the end automatically closes the search. It should not do that. I have some issues with the price slider too where sometimes it doesn't seem to work (the bar doesn't light up white and it gives no results) - but this doesn't happen every time. Trying to see if I can figure out what I'm doing that causes it. Tried to take a screen recording of it and tested in both Safari and Brave with similar issues.
https://user-images.githubusercontent.com/59464107/223206625-880dc9f0-64a3-4e56-b762-876ba4ba9278.mov

(Github doesn't seem to like my screen recording, I can send it over Slack if needed)

Appears if you drag the slider to the end slowly it's fine, but I keep triggering it to close by going just a bit beyond or too quick (if that makes sense). It's just really jarring when it does this especially since you're adjusting to see the results, not have it close on you.

**Review by stephclarkga — CHANGES_REQUESTED** [review]
Double sliders look better and work well 👍🏻 Only thing is when the boxes are unchecked, I think the slider should be gray showing it's inactive and right now it is staying white? 
Screen Shot 2023-03-07 at 11 31 10 AM

**Review by ericsharma — CHANGES_REQUESTED** [review]
@IYTEC We shouldn't be repeating code like we do for `filterReducer`. The same code is found in both `MobileSearchSideBar.jsx` and `SearchSidebar.jsx` 
It is bad practice to repeat yourself in this way and affects the readability for both components. Instead you should abstract the logic for filterReducer into its own file and then import it wherever it is needed.

**Review by ericsharma — APPROVED** [review]

**Pull request merged**
