### PR TITLE
Issue 888 🎨 feature update the layout when no wallet is connected

### LINKED ISSUE #888: 🎨 Feature: Update the layout when no wallet is connected
# ℹ Overview

When no wallet is connected, instead of having blank sections, add text overlay to the "Orders" section and change the text in the "Place Order" section to be more descriptive than it currently is with just "Not signed in". 

Screen Shot 2022-12-09 at 12 33 00 PM

https://www.figma.com/file/AnckPL76NcZCJAuzOiWCNX/Algodex-Interface-Guide?node-id=1872%3A636&t=4YLkeYwtR40GCXe6-1

### PR DESCRIPTION
**Pull request by IYTEC**
# ℹ Overview
Empty state across app when no wallet is connected

### 📝 Related Issues
- closes #888 

### 🔐 Acceptance:

- [ ] `yarn test` passes

### CODE REVIEW

**Comment by atrefonas** [comment]
I'm not sure it looks good on small laptop screens. What do you think? Maybe it should take up more width or smaller font

image

**Comment by atrefonas** [comment]
See above @stephclarkga @IYTEC

**Review by stephclarkga — CHANGES_REQUESTED** [review]
Mostly looks good - only change I would make is less padding in the Orders section (mostly on screens below 1440px wide). It would be better to not exceed 3 lines of text for the top line. Probably 50% less padding on each side for small screens. 

This is what it looks like on a 1440px display:
Screen Shot 2022-12-13 at 9 30 29 AM

Larger screens (I think around 1700px) when the top line drops down to 3 lines look fine though and I wouldn't change that 👍🏻

**Comment by stephclarkga** [comment]
> I'm not sure it looks good on small laptop screens. What do you think? Maybe it should take up more width or smaller font
> 
> image


I was typing that up and missed you comment but looks like we agreed @atrefonas. I would try to expand the width before changing the font. (better if the fonts match the other two sections)

**Review by stephclarkga — APPROVED** [review]
Looks good 👍🏻

**Review by stephclarkga — APPROVED** [review]

**Pull request merged**
