### PR TITLE
💬 Update title in About Page

### PR DESCRIPTION
**Pull request by alchemist-bounty**
# ℹ Overview

Update the About Page title

### 🔐 Acceptance:

- [ ] `yarn test` passes
- [ ] Uses Unicode conventional commits [gitmoji](https://gitmoji.dev/)

### CODE REVIEW

**Review by ramyatrefonas — CHANGES_REQUESTED** [review]
add titles to support and Docs page

**Review by atrefonas — APPROVED** [review]

**Review by ramyatrefonas — APPROVED** [review]

**Comment by ramyatrefonas** [comment]
Hi Giuseppe,

Please make the support and docs page title like the trade page title.

Ramya

**Comment by IYTEC** [comment]
@ramyatrefonas I will add this fix to UI Fixes here

https://github.com/algodex/algodex-react/issues/766

**Comment by ramyatrefonas** [comment]
Looks good

**Pull request merged**
