### PR TITLE
⚡️Enhance modal

### LINKED ISSUE #731: 🎨 Minor Updates to "Welcome Modal"
# ℹ Overview

Couple updates to this modal -

Screen Shot 2022-08-25 at 2 13 53 PM

1. "Algos" should always be capitalized (it appears like that is the general use of it). I think we should also capitalize "Testnet" in "Testnet Algos".

2. Let's also add "using our support page" to the end of "Please send feedback about any bugs or feature requests!" so "Please send feedback about any bugs or feature requests to our support page!"

3. Also the spacing between the social icons and the line above them should match the spacing around "Faucet" and "Documentation". It's a bit tight there.

### PR DESCRIPTION
**Pull request by IYTEC**
# ℹ Overview
Add updates to welcome modal

### 📝 Related Issues
- closes #731 

### 🔐 Acceptance:

- [ ] `yarn test` passes

### CODE REVIEW

**Review by atrefonas — APPROVED** [review]

**Review by stephclarkga — CHANGES_REQUESTED** [review]
Couple things -  

1. Just the first letter of "Algos" and "Testnet" or "Mainnet" should be capitalized - not the whole word.

2. It was the vertical spacing of the social icons that should be equal from the lines between "Faucet" and "Documentation" ("Disclaimer" and "Documentation" in Mainnet). The icons are now too spread out horizontally. They should be around 12px apart from each other and about 20px below the line above them and then the "Accept" button is 36 px below the social icons but centered. I have the spacing in the Figma file but here's a screen shot too:
 Screen Shot 2022-08-29 at 3 05 07 PM

**Review by atrefonas — CHANGES_REQUESTED** [review]
Please address @stephclarkga 's comments

**Review by stephclarkga — CHANGES_REQUESTED** [review]
These icons are still too far apart: 
Screen Shot 2022-09-07 at 12 02 32 AM

They should look more like this: (I have them 12px apart in the design)

Screen Shot 2022-09-07 at 12 04 21 AM

**Comment by IYTEC** [comment]
This is fixed in the current build.

**Pull request closed without merging**
