### PR TITLE
✨ Show amount when there are more decimals

### LINKED ISSUE #613: 🐛 Fix: Show amounts to more decimals when it is all leading 0's.
# ℹ Overview

Show amounts to more decimals when it is all leading 0's. 

image

### 💻 System Configuration

- Operating System:
    - Edition: 
    - Version: 
    - Build: 
- Browser:
    - Type: 
    - Version:

### PR DESCRIPTION
**Pull request by IYTEC**
# ℹ Overview
Asset amount should have a leading figure in trade history

### 📝 Related Issues
- closes #613 

### 🔐 Acceptance:

- [ ] `yarn test` passes
- [ ] Uses Unicode conventional commits [gitmoji](https://gitmoji.dev/)

### CODE REVIEW

**Review by atrefonas — CHANGES_REQUESTED** [review]
See comment

**Review by atrefonas — APPROVED** [review]
Definitely an improvement

**Review by atrefonas — CHANGES_REQUESTED** [review]

**Review by atrefonas — CHANGES_REQUESTED** [review]
I don't think this looks good. Can we only show exponential values when it is E-5 or E-6 or greater? Otherwise show in regular format.

image

**Review by atrefonas — CHANGES_REQUESTED** [review]
I see here: 100000.000000E-0

https://algodex-react-dvkkwgk40-algodex-dev.vercel.app/trade/94115664?cc=US

Please fix. E-0 is equal to one. So it should just say 100000.000000.

**Comment by IYTEC** [comment]
Fixed in Latest build. @atrefonas if issue persist, we can create a new issue

**Pull request closed without merging**
