### PR TITLE
1003 update managetoken component

### LINKED ISSUE #1003: Update ManageToken component
# ℹ️ Overview 

@stephclarkga I think that when a user clicks on an editable field there should be some type of visual icon (perhaps a checkmark next to the x) that the user can click to submit the changes. Right now it works if you hit enter. What do you think? 

Manage token form editing is still buggy please see [video](https://www.loom.com/share/b854c426555d47deb2220c4d34a4e29c) for unexpected behavior. 

@treasurechic When editing an input field, input validation happens when submitting a change, but not when the user clicks the x button. When a user clicks the x button the input field should revert to whatever was there before it. Also [per the documentation](https://developer.algorand.org/docs/get-details/asa/#modifying-an-asset) can you change the behavior so that the editable fields are only editable when the Manager Account matches the Connected Wallet? See screen shot below 

Screen Shot 2023-03-08 at 4 10 40 PM

### PR DESCRIPTION
**Pull request by treasurechic**
# ℹ Overview
closes #1003 

### 🔐 Acceptance:

- [ ] `yarn test` passes

### CODE REVIEW

**Review by ericsharma — CHANGES_REQUESTED** [review]
Only the active editable field should be in focus. If I click edit on a second field then the first field should automatically close. See below screen shot for incorrect behavior. Only the field that the user most recently clicked should be in the editing state. 

Screen Shot 2023-03-10 at 8 34 06 AM

**Comment by treasurechic** [comment]
@ericsharma I don't think this behavior is really cool for the users tho. So what if a user is editing a field but has not yet clicked "cancel" or "confirm" on that field but proceeds to click the "edit" icon of another field, with the intention of clicking the "confirm" button on each field after pasting all the addresses in.  

So according to your request now, what do you think I should do for this user?.... Cancel the current input? (which will revert to the old address) or confirm the current input(which will save the address on the input UI).

IMO, I think it is ok for users to be able to edit multiple fields at the same time.

**Comment by ericsharma** [comment]
@treasurechic There is no reason for a user to have multiple editable fields open at the same time, what would be the purpose? There is no button to submit edits in bulk so why have the option to have multiple editable fields if you have to explicitly confirm each individual one? In my opinion it is bad UI and just opens up more surface area for unexpected behavior. I'm not sure why a user would ever want to do this. 
And to answer your question: If a user does not explicitly hit confirm then you revert the field to what was there before. 

@stephclarkga Perhaps you can weigh in? I'd defer to your judgement since this is your area of expertise.

**Comment by ericsharma** [comment]
@stephclarkga Any update on this? PR is waiting for your feedback.

**Comment by stephclarkga** [comment]
I agree that only one field should be in the editing state at a time and if an entry is not confirmed when another is open, it should revert to the previous address. I also like the idea of only having one editable field at a time since it helps ensure the users actually hit the check to submit the change instead of editing and just hitting the final submit button overall

I think we need something to show that the address was changed (before they click the main button to send to blockchain) to give confirmation and call out that it was updated. Maybe if an address is edited, it could be shown in green until submitted? I also wonder if we need to add a call out once an address is edited to remind the user that they need to submit the changes to the blockchain to finalize it.

**Comment by treasurechic** [comment]
@stephclarkga pls can you update the ui with the illustration of the second paragraph of your comment. So I can update the interface accordingly.

**Comment by stephclarkga** [comment]
@treasurechic I updated the Figma with this:
Screen Shot 2023-03-14 at 10 01 15 AM

If any field is edited, when the edit field is closed, this info message shows up below it. I changed my mind about the addresses being a different color though- I think it reads fine in white with the call out message below it. I also added some text to the general callout above the  "Update Token" button.

**Comment by stephclarkga** [comment]
@treasurechic Trying to view the "Manage Token" page but I'm getting this error when I have a wallet connected and try to view that page: Screen Shot 2023-03-15 at 11 54 51 AM
Screen Shot 2023-03-15 at 11 54 32 AM

Without a wallet connected, I can view the page but there's not assets to select from

**Comment by treasurechic** [comment]
@stephclarkga this is because the wallet you connected with has no "created asset" it can manage. 

A fix has been deployed for this error. Pls test again.

However, If you haven’t created an asset with the connected wallet, you will have no asset to select from as you can’t manage an asset you did not own or assigned as its manager.

**Comment by stephclarkga** [comment]
Ah, I figured that might be the case. I can view the page with the wallet connected now so that's good. I did try to create a token but wasn't sure if that was working. Just tried again and got this weird error: 
Screen Shot 2023-03-15 at 1 16 36 PM
Screen Shot 2023-03-15 at 1 18 50 PM

**Comment by treasurechic** [comment]
@stephclarkga I will test and get back to you on this create token error. 

For you to proceed with your test on the manage token page, you can create a token with your wallet on another platform so you can have assets to test with.

**Review by stephclarkga — CHANGES_REQUESTED** [review]
Editing the fields works well 👍🏻 I wasn't able to submit the update (button didn't do anything?) but I assume that hasn't been done yet?

Couple small design things:

1. Can you add a little space between the wallet address and the copy button? (probably 4px). Just makes it a little more readable. Should be similar spacing to the creator wallet address at the top in the box.
Screen Shot 2023-03-15 at 2 13 26 PM

2. I think the "total supply" is display with a comma instead of a decimal. This asset I created has a total of 16 but it shows as 16,000,000. I think all created assets have to be a whole number so I think it's best for it to show the total supply without any decimals (since we have the decimal number in the next line) but let me know if that's not possible or why it's showing like this.
Screen Shot 2023-03-15 at 2 14 50 PM

**Comment by treasurechic** [comment]
@stephclarkga yes, the button is not connected to the actual update yet.

The total supply was a wrong calculation on my part which I have fixed and updated.
Yes, the total supplies are whole numbers no decimal is allowed.

**Review by stephclarkga — APPROVED** [review]
Looks good now! 👍🏻

**Pull request merged**
