### PR TITLE
Issue 931 feature launch pad components

### LINKED ISSUE #931: Feature: Launch pad components
# ℹ Overview

### LINKED ISSUE #944: Merge launchpad designs and address any merge conflicts

### PR DESCRIPTION
**Pull request by treasurechic**
# ℹ Overview

closes #931

closes #944 

### 🔐 Acceptance:

- [ ] `yarn test` passes

### CODE REVIEW

**Review by ericsharma — CHANGES_REQUESTED** [review]
@treasurechic Thanks for changing the source for the PR and addressing the merge conflicts. I had a quick discussion with @stephclarkga and we have decided on some minor updates to the design. Once they are ready I think Steph will reach out to you with more details!

**Review by stephclarkga — CHANGES_REQUESTED** [review]
Couple changes in the design - Figma file has been updated: 

In the "Manage token" page, the addresses that were in "Advanced Options" are not editable so if the asset has one it will show in the static table (Like the asset URL or hash)
Screen Shot 2023-02-08 at 12 30 13 AM

Appears like having a time to close and start a sale is technically challenging to sign so removed any time settings on the sale page and the manage sale page shown here:
Screen Shot 2023-02-08 at 12 31 24 AM


https://www.figma.com/file/h8ghYImSd6atpjl5qavhW1/Algodex-Token-Launchpad?node-id=0%3A1&t=ZktkAV5CqujDvrhl-1

**Comment by treasurechic** [comment]
@stephclarkga , are the token name, token supply and decimals editable?

image

**Comment by ericsharma** [comment]
@treasurechic Name, Decimals, and Token supply are not editable after creation.

**Review by stephclarkga — APPROVED** [review]

**Pull request merged**
