### PR TITLE
:zap: Update editable fields

### LINKED ISSUE #989: Update editable fields for manageToken component
# ℹ️ Overview
[Per Algorand Documentation](https://developer.algorand.org/docs/get-details/asa/#modifying-an-asset) only clawback, reserve, manager, and freeze fields can be edited after asa creation so remove the edit icon from asset url and add it to the editable fields. 

Screen Shot 2023-02-28 at 3 38 02 PM

### PR DESCRIPTION
**Pull request by treasurechic**
# ℹ Overview
closes #989 

### 🔐 Acceptance:

- [ ] `yarn test` passes

### CODE REVIEW

**Review by ericsharma — CHANGES_REQUESTED** [review]
This is a good start but I think the UX needs to be polished for the editable fields. At the very least there needs to be a way to exit "editing mode". Perhaps when the input field is no longer in focus. 
Other things to add:
Maybe a way to visually differentiate between the fields that have been changed before clicking the update token button.
@treasurechic Can you also add input validation to ensure the user is inputting a valid algorand address?  
@stephclarkga Maybe you have some ideas related to this?

**Comment by stephclarkga** [comment]
Agreed with what @ericsharma says above. Definitely need a way to close the edit mode. Probably just need to add an icon (X) to the right of the box. I'll update it in Figma.

I want to make sure that I'm viewing the correct thing. Are the clawback/reserve/freeze/manager addresses actually editable? I thought they weren't but the URL should be?

**Comment by treasurechic** [comment]
> Agreed with what @ericsharma says above. Definitely need a way to close the edit mode. Probably just need to add an icon (X) to the right of the box. I'll update it in Figma.
> 
> I want to make sure that I'm viewing the correct thing. Are the clawback/reserve/freeze/manager addresses actually editable? I thought they weren't but the URL should be?

Yea, they are editable and the asset URL is not according to the [documentation](https://developer.algorand.org/docs/get-details/asa/#modifying-an-asset)

**Comment by stephclarkga** [comment]
@treasurechic Awesome, good to know! Thanks!

**Comment by ericsharma** [comment]
@stephclarkga [They are editable](https://developer.algorand.org/docs/get-details/asa/#modifying-an-asset) but only by the designated manager account. . I'm working on logic that encapsulates this so the end user can only edit assets that they are allowed to edit.

**Review by ericsharma — APPROVED** [review]

**Pull request merged**
